// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/career/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/career">> = Specific
  const handler = {} as typeof import("../../../app/career/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/learning-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning-lab">> = Specific
  const handler = {} as typeof import("../../../app/learning-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nlp-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nlp-lab">> = Specific
  const handler = {} as typeof import("../../../app/nlp-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pdf-reader/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pdf-reader">> = Specific
  const handler = {} as typeof import("../../../app/pdf-reader/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projekt-fahrplan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projekt-fahrplan">> = Specific
  const handler = {} as typeof import("../../../app/projekt-fahrplan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/attachments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/attachments">> = Specific
  const handler = {} as typeof import("../../../app/api/attachments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/connections/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/status">> = Specific
  const handler = {} as typeof import("../../../app/api/connections/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/drive/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drive/public">> = Specific
  const handler = {} as typeof import("../../../app/api/drive/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expose/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expose">> = Specific
  const handler = {} as typeof import("../../../app/api/expose/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/focus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/focus">> = Specific
  const handler = {} as typeof import("../../../app/api/focus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/auth">> = Specific
  const handler = {} as typeof import("../../../app/api/google/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/calendar">> = Specific
  const handler = {} as typeof import("../../../app/api/google/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/callback">> = Specific
  const handler = {} as typeof import("../../../app/api/google/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/disconnect">> = Specific
  const handler = {} as typeof import("../../../app/api/google/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/drive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/drive">> = Specific
  const handler = {} as typeof import("../../../app/api/google/drive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/gmail/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/gmail">> = Specific
  const handler = {} as typeof import("../../../app/api/google/gmail/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/google/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/google/status">> = Specific
  const handler = {} as typeof import("../../../app/api/google/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/learning-lab/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning-lab/health">> = Specific
  const handler = {} as typeof import("../../../app/api/learning-lab/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/learning-lab/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning-lab/progress">> = Specific
  const handler = {} as typeof import("../../../app/api/learning-lab/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pdf/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pdf/public">> = Specific
  const handler = {} as typeof import("../../../app/api/pdf/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/status">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/providers">> = Specific
  const handler = {} as typeof import("../../../app/api/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/state/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/state">> = Specific
  const handler = {} as typeof import("../../../app/api/state/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../../app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/study-sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/study-sessions">> = Specific
  const handler = {} as typeof import("../../../app/api/study-sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/translate">> = Specific
  const handler = {} as typeof import("../../../app/api/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/nlp-lab/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/nlp-lab">> = Specific
  const handler = {} as typeof import("../../../app/nlp-lab/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pdf-reader/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/pdf-reader">> = Specific
  const handler = {} as typeof import("../../../app/pdf-reader/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/projekt-fahrplan/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projekt-fahrplan">> = Specific
  const handler = {} as typeof import("../../../app/projekt-fahrplan/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/settings/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/settings/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
