// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/career" | "/learning-lab" | "/nlp-lab" | "/pdf-reader" | "/projekt-fahrplan" | "/settings"
type AppRouteHandlerRoutes = "/api/ai" | "/api/attachments" | "/api/connections/status" | "/api/drive/public" | "/api/expose" | "/api/focus" | "/api/google/auth" | "/api/google/calendar" | "/api/google/callback" | "/api/google/disconnect" | "/api/google/drive" | "/api/google/gmail" | "/api/google/status" | "/api/learning-lab/health" | "/api/learning-lab/progress" | "/api/pdf/public" | "/api/platform/status" | "/api/providers" | "/api/settings" | "/api/state" | "/api/status" | "/api/study-sessions" | "/api/translate"
type PageRoutes = never
type LayoutRoutes = "/" | "/nlp-lab" | "/pdf-reader" | "/projekt-fahrplan" | "/settings"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai": {}
  "/api/attachments": {}
  "/api/connections/status": {}
  "/api/drive/public": {}
  "/api/expose": {}
  "/api/focus": {}
  "/api/google/auth": {}
  "/api/google/calendar": {}
  "/api/google/callback": {}
  "/api/google/disconnect": {}
  "/api/google/drive": {}
  "/api/google/gmail": {}
  "/api/google/status": {}
  "/api/learning-lab/health": {}
  "/api/learning-lab/progress": {}
  "/api/pdf/public": {}
  "/api/platform/status": {}
  "/api/providers": {}
  "/api/settings": {}
  "/api/state": {}
  "/api/status": {}
  "/api/study-sessions": {}
  "/api/translate": {}
  "/career": {}
  "/learning-lab": {}
  "/nlp-lab": {}
  "/pdf-reader": {}
  "/projekt-fahrplan": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/nlp-lab": never
  "/pdf-reader": never
  "/projekt-fahrplan": never
  "/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
