export { DAILY_PRACTICE_STEPS, type DailyPracticeStep } from "./practice-plan";
export {
  allocateCoreMissionMinutes,
  buildDailyAutomaticityProgram,
  buildAdaptiveDailyPlan,
  calculateDailyProgress,
  type AdaptiveDailyBlock,
  type AdaptiveDailyPlan,
  type AdaptiveDailySignals,
  type DailyAutomaticityBlock,
  type DailyAutomaticityBlockId,
  type DailyAutomaticityProgram,
  type DailyBlockId,
  type DailyMissionKind,
  type DailySessionMinutes,
  DAILY_SESSION_OPTIONS,
} from "./adaptive-daily-plan";

export {
  appendLearningEvidenceBundleToStorage,
  buildAttemptVerticalSlice,
  isLearningMode,
  LEARNING_EVIDENCE_STORAGE_KEY,
  LEARNING_SCHEMA_VERSION,
  readLearningEvidenceLedger,
  type AttemptVerticalSliceInput,
  type ContentUnit,
  type DailyPracticePlan,
  type EvidenceRecord,
  type LearnerResponse,
  type LearningDomainEvent,
  type LearningEvidenceBundle,
  type LearningEvidenceLedger,
} from "@automaticity/learning-core";
export {
  REVIEW_INTERVAL_DAYS,
  getNextReviewDate,
  getReviewProgressAfterResult,
  type ReviewConfidence,
  getReviewSchedule,
  type ReviewProgress,
} from "./review-scheduler";
export {
  applyLanguageToolMatches,
  classifyError,
  evaluateAnswer,
  getTaskIssues,
  offlineCorrect,
  targetEvidencePresent,
  type EvaluationIssue,
  type EvaluationKind,
  type EvaluationNextAction,
  type EvaluationReport,
  type GrammarTarget,
  type LanguageToolMatch,
  type LanguageToolResult,
} from "./evaluation";
export {
  AUTOMATICITY_LATENCY_THRESHOLD_MS,
  MASTERY_MODES,
  MASTERY_STATUSES,
  PRACTICE_STAGE_REGRESSION_MARGIN,
  PRACTICE_STAGE_TARGET_ACCURACY,
  WRITING_LATENCY_THRESHOLD_MS,
  calculateAutomaticityScore,
  calculateMasteryStatus,
  createEmptyMasteryRecord,
  masteryStatusLabels,
  median,
  nextPracticeStage,
  recordMasteryAttempt,
  recordMasteryReview,
  recordVerifiedMasteryAttempt,
  setMasteryCriticalErrors,
  type MasteryAttempt,
  type MasteryMode,
  type MasteryRecord,
  type MasteryScores,
  type MasteryStatus,
  type VerifiableMasteryAttempt,
} from "./mastery";
export {
  AUTOMATIZATION_MATRIX_COLUMNS,
  AUTOMATIZATION_MATRIX_WEEKS,
  AUTOMATIZATION_MODULES,
  SHADOWING_STAGES,
  automatizationModuleLabels,
  buildAutomatizationTopic,
  computeAutomatizationMatrix,
  parseAutomatizationTopic,
  shadowingStageLabels,
  type AutomatizationMatrixCell,
  type AutomatizationMatrixColumn,
  type AutomatizationMatrixColumnKey,
  type AutomatizationMatrixRow,
  type AutomatizationModule,
  type ParsedAutomatizationTopic,
  type ShadowingStage,
} from "./automatization";
export {
  CEFR_LEVELS,
  CURRENT_STORAGE_KEY,
  ERROR_CLASSES,
  LEGACY_STORAGE_KEY,
  PLACEMENT_MODES,
  REPAIR_STATUSES,
  REVIEW_MODES,
  REVIEW_SOURCE_TYPES,
  calculateStreak,
  canCompleteDailyStep,
  completeDailyPlanStep,
  countWords,
  createInitialLearnerState,
  errorClassLabels,
  getDailyPlan,
  getTodayKey,
  migrateLegacyLearnerState,
  normalizeFlashcards,
  normalizeLearnerState,
  repairStatusLabels,
  reviewModeLabels,
  type DailyPlanRecord,
  type ErrorClass,
  type ErrorRecord,
  type FlashcardGrade,
  type FlashcardMode,
  type FlashcardRecord,
  type FlashcardScheduleState,
  type FlashcardSource,
  type CefrLevel,
  type LearnerProfilePreferences,
  type LearnerSettings,
  type LearnerState,
  type OutcomeEvidence,
  type PlacementMode,
  type RepairStatus,
  type ReviewRecord,
  type ReviewMode,
  type ReviewSourceType,
  type SessionRecord,
  type TodayGrammarRecord,
  type UserAttempt,
} from "./learner-state";
